from . import pagina_inicial
from . import sobre
from . import cadastro
from . import jornada
from . import dashboard
from . import registro
from . import tabela
from . import download
from . import jornada_contratual
from . import calculadora